name: Auto Deploy to Cloudflare Pages

on:
  push:
    branches:
      - production
  schedule:
    # 毎週 月・木 の10:00（JST）に実行（UTCでは1:00）
    - cron: '0 1 * * 1,4'

  workflow_dispatch:  # 手動実行

env:
  NODE_VERSION: 22.15.0
  PNPM_VERSION: 10.10.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm ${{ env.PNPM_VERSION }}
        run: npm install -g pnpm@${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          directory: pages deploy dist --project-name=${{ secrets.CF_PROJECT_NAME }}
